name: Simple Test Workflow

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore Lab3.sln
      
    - name: Build solution
      run: dotnet build Lab3.sln --configuration Release --no-restore
      
    - name: Run tests
      run: dotnet test Lab3.sln --configuration Release --no-build --verbosity normal
