name: Simple Test Workflow

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies - Lab 3
      run: dotnet restore lab3files/Lab3.sln
      
    - name: Restore dependencies - Lab 4
      run: dotnet restore lab4files/Lab4.sln
      
    - name: Build solution - Lab 3
      run: dotnet build lab3files/Lab3.sln --configuration Release --no-restore
      
    - name: Build solution - Lab 4
      run: dotnet build lab4files/Lab4.sln --configuration Release --no-restore
      
    - name: Run Lab 3 SpecFlow tests
      run: dotnet test lab3files/Lab3.sln --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=lab3-test-results.trx" --results-directory ./TestResults
      
    - name: Run Lab 4 Unit tests with Mocking
      run: dotnet test lab4files/Lab4.sln --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=lab4-test-results.trx" --results-directory ./TestResults
      
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx
